# Generated by Django 4.0.3 on 2022-03-20 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_img', models.ImageField(upload_to='static/img/')),
                ('game_name', models.CharField(max_length=250)),
                ('gamers_count', models.CharField(max_length=100)),
                ('game_time', models.CharField(max_length=50)),
                ('game_year', models.CharField(max_length=50)),
                ('price_day', models.IntegerField()),
                ('price_week', models.IntegerField()),
                ('categories', models.CharField(max_length=500)),
            ],
        ),
    ]
