# Generated by Django 4.0.3 on 2022-03-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_description_alter_product_main_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='second_img',
            field=models.ImageField(null=True, upload_to='main/static/img'),
        ),
        migrations.AddField(
            model_name='product',
            name='third_img',
            field=models.ImageField(null=True, upload_to='main/static/img'),
        ),
    ]
