# Generated by Django 4.0.3 on 2022-03-25 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_basket_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='rental',
            new_name='rental_time',
        ),
    ]
