# Generated by Django 4.0.3 on 2022-03-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='user_adress',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
