# Generated by Django 4.0.3 on 2022-03-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_check_user_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='bill_id',
            field=models.IntegerField(null=True),
        ),
    ]
