# Generated by Django 4.0.3 on 2022-03-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_check_bill_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
