# Generated by Django 4.0.3 on 2022-03-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_check_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='order_info',
            new_name='order_games',
        ),
        migrations.AddField(
            model_name='orders',
            name='get_method',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_method',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='total_price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='user_adress',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
