# Generated by Django 4.0.3 on 2022-03-31 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_orders_order_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='order_games',
        ),
        migrations.AddField(
            model_name='check',
            name='order_game_names',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='check',
            name='order_game_rentals',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
