# Generated by Django 4.0.3 on 2022-03-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_check_order_games_check_order_game_names_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='check',
            name='order_game_names',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='check',
            name='order_game_rentals',
            field=models.CharField(max_length=500),
        ),
    ]
