# Generated by Django 4.0.3 on 2022-03-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_check_order_game_names_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='order_game_names',
        ),
        migrations.RemoveField(
            model_name='check',
            name='order_game_rentals',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='order_games',
        ),
        migrations.AddField(
            model_name='check',
            name='order_games',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_game_names',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_game_rentals',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
