# Generated by Django 4.0.3 on 2022-04-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_check_order_game_names_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Baners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baner_game_id', models.IntegerField()),
                ('baner_img', models.ImageField(upload_to='main/static/img/')),
            ],
        ),
    ]
