# Generated by Django 4.0.3 on 2022-04-02 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_baners'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
