# Generated by Django 4.0.3 on 2022-04-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_comments_date_alter_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.CharField(default='06.04.2022', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.CharField(default='06.04.2022', max_length=200, null=True),
        ),
    ]
